# WITH - 재귀적 CTE 사용
WITH RECURSIVE HIERARCHY AS (
    # 최상위 개체
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    # 다음 계층 개체
    SELECT A.ID, A.PARENT_ID, B.GENERATION + 1
    FROM ECOLI_DATA AS A
    JOIN HIERARCHY AS B
    ON A.PARENT_ID = B.ID
)

SELECT COUNT(*) AS COUNT, A.GENERATION
FROM HIERARCHY AS A # 부모
LEFT JOIN HIERARCHY AS B # 자식
ON A.ID = B.PARENT_ID # 부모 A의 ID와 자식 B의 PARENT_ID가 일치하는 데이터에 매핑
WHERE B.ID IS NULL # 자식 B의 부모와 매칭이 안되므로 B의 데이터는 NULL이 들어감
GROUP BY GENERATION
ORDER BY GENERATION