WITH JOIN2021 AS (
    SELECT USER_ID, DATE_FORMAT(JOINED, "%Y-%m-%d") AS JOINED
    FROM USER_INFO
    WHERE JOINED LIKE "2021%"
    ORDER BY USER_ID
),
SALE2021 AS (
    SELECT A.USER_ID, DATE_FORMAT(B.SALES_DATE, "%Y-%m-%d") AS SALES_DATE
    FROM USER_INFO AS A
    JOIN ONLINE_SALE AS B
    ON A.USER_ID=B.USER_ID
    WHERE A.JOINED LIKE "2021%"
    ORDER BY USER_ID ASC
)

SELECT
    DATE_FORMAT(B.SALES_DATE, "%Y") AS YEAR,
    DATE_FORMAT(B.SALES_DATE, "%m") AS MONTH,
    COUNT(DISTINCT B.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT B.USER_ID) / (SELECT COUNT(*) FROM JOIN2021), 1) AS PUCHASED_RATIO
FROM JOIN2021 AS A
LEFT JOIN SALE2021 AS B
ON A.USER_ID=B.USER_ID
WHERE B.SALES_DATE IS NOT NULL
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC;