WITH BS AS (
    SELECT BOOK_ID, SUM(SALES) AS SUM_SALES
    FROM BOOK_SALES
    WHERE SALES_DATE LIKE '2022-01%'
    GROUP BY BOOK_ID
)

SELECT D.AUTHOR_ID, D.AUTHOR_NAME, D.CATEGORY, SUM(A.SUM_SALES * D.PRICE) AS TOTAL_SALES
FROM BS AS A
JOIN 
(
    SELECT B.BOOK_ID, B.CATEGORY, B.AUTHOR_ID, C.AUTHOR_NAME, B.PRICE
    FROM BOOK AS B
    JOIN AUTHOR AS C
    ON B.AUTHOR_ID=C.AUTHOR_ID
) AS D
ON A.BOOK_ID=D.BOOK_ID
GROUP BY D.AUTHOR_NAME, D.CATEGORY
ORDER BY D.AUTHOR_ID, D.CATEGORY DESC;