SELECT
    A.CAR_ID,
    A.CAR_TYPE,
    ROUND(A.DAILY_FEE * (1 - B.DISCOUNT_RATE / 100) * 30, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS B
ON A.CAR_TYPE=B.CAR_TYPE
WHERE (A.CAR_TYPE = 'SUV' OR A.CAR_TYPE = '세단')
AND A.CAR_ID NOT IN
(
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= "2022-11-30" AND END_DATE >= "2022-11-01"
)
AND B.DURATION_TYPE LIKE "30%"
AND ROUND(A.DAILY_FEE * (1 - B.DISCOUNT_RATE / 100) * 30) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;